/*
IT IS AN OBJECT ORIENTATE PROGRAMMING.
IN THIS WE CAN USE SOME OTHER CLASS PROPERTIES USING AN OBJECT .
IT HAS TWO MAJOR PROPERTIES LIKE
i. STATE
ii. FUNCTIONALITY

THIS BASE ON REAL WORLD THINGS
IN FIRST ONE IT IS STATE, EG.- CAR

IN THE CAR WE HAVE SOME STATE THAT IS CAR COLOR, NAME, MODEL, DOORS ETC. TIER THEY AER JUST STATE

AND IN SECOND ONES WE HAVE LIKE CAR MOVING, STOP, TIER ROTATION ETC. THEY ARE THE FUNCTIONALITY.
AND ALWAYS IF WE CREAT A CLASS PROPERTIES FOR OBJECT USE THEN WE HAVE TO INITIALIZE THE DEFAULT VALUE TO THAT PROPERTIES.
IT CAN CONTAIN ALL THE THING OF THAT CLASS LIKE METHODS, FUNCTIONALITY , VARIABLES ETC.

NOTE : WE ONLY USE PROPERTIES OF THAT CLASS NOT THE PARAMETER, ONLY WE PASS THE VALUE DIRECT AND IT SORE AS STATE OF THE VARIABLE
IF WE WANT SOME VALIDATION BEFORE PASSING THE VALUE THEN THIS IS NOT WORK,
WE HAVE TO CREATE A PARAMETER THEN DECLARE A VARIABLE ON THAT CLASS AND DO SOME VALIDATION THEN WE CAN USE THIS

WE CAN USE CAR CLASS IN OTHER FILES. AND CALL IT HERE IN THIS FUNCTION AND IT WORK FINE
BECAUSE WHAT IF WE HAVE TO MANY CODE LINE IN OUR CLASS THEN THIS IS NOT FORMALIZE CODE.
THERE IS SOME PATTERN TO LOOK OUR PROJECTS CLEAN AND EFFICIENT PATTERN TO WORK WITH IT.
BOTH PATTERN ARE WORKING BUT THE FIRST ONE IS NOT PATERNALIZE .

WE CAN USE THESE PROPERTIES USING THE OBJECT BELOW IS THE EXAMPLE
*/

fun main(){

    val car = Car() // THIS IS OUR OBJECT, USING THAT OBJECT WE CAN USE CAR CLASS PROPERTIES

    // WE HAVE TO DEFINE A VALUE OTHERWISE IT GIVE BLANK BECAUSE WE INIT THE STATE BUT NOT WITH VALUE
    car.name = "Ford"
    car.model = "SG23"
    car.doors = 2

    // IN THE BELOW CODE PRINTLN WE USE IT STATE
    println("CAR NAME :- ${car.name}")  // IN THIS WE USE DOT NOTATION USING THAT AND OBJECT NAME WE CAN USE OTHER CLASS PROPERTIES
    println("THE MODEL IS :- ${car.model }")
    println("DOORS :- ${car.doors }")

    // THEN HERE WE USE ITS FUNCTIONALITY
    car.carStatus()

    println("\n") // IT IS GIVE ONE MORE EXTRA LINE SPACE IN BETWEEN THOSE TWO
    println("USE PARAMETERS FOR THE VALUES")
    println("\n")
    // HERE WE USE THE PARAMETERS TO PASS THE VALUE FOR THAT PROPERTIES
    val car1 = Car1( "BMW", "S23", 4, true) // WE PASS THE VALUE TO THAT PARAMETERS

    println("CAR NAME :- ${car1.name}")
    println("THE MODEL IS :- ${car1.model }")
    println("DOORS :- ${car1.doors }")

    car1.carStatus1()

    println("\n")
    println("THE BELOW ONE IS INITIALIZE BLOCK ")
    println("\n")

    val user = User("Anil", "Prajapat", 25)

    println("USER AGE IS :- ${user.age}")


}

class Car(){

    var name = ""
    var model = ""
    var doors = 0
    var isActive = false

    fun carStatus(){
        if (isActive)
            println("THE CAR IS START")
        else
            println("THE CAR IS STOPPED")
    }

}

/*THERE IS ONE MORE TYPE OF WRITE THIS CODE USING PARAMETER , WHY?? IF WE HAVE MULTIPLE STATE OF SOME OBJECT THEN,
 IT'S HARD TO WRITE EVERY LINE OF CODE MULTIPLE TIME LIKE 100 AND 10000 TIMES
SO WE USS THIS , TO PASS THE PARAMETER ONES.
 */


class Car1(var name: String, var model: String, var doors: Int, var isActive: Boolean){

    // IN ABOVE CODE WE DECLARE VAR, WHY?? BECAUSE IF WE NOT DECLARE THE THEN IT ONLY HOLD THE VALUE BUT NOT IN STATE, FOR THE STATE WE DECLARE AS A VAR .
    // USING VAR WE CHANGE THE PARAMETER TO PROPERTIES

    fun carStatus1(){
        if (isActive)
            println("THE CAR IS START")
        else
            println("THE CAR IS STOPPED")
    }

}

/*
IN THIS BELOW CLASS WE INITIALIZER BLOCK , ITS SHORT FORM IS init.
WE USE THIS BECAUSE THERE ARE SOME CONDITION THAT WE HAVE TO CHECK FIRST IN THE EXECUTION OF THE CODE
IT WILL INITIALIZE THAT CODE WHICH IS WRITTEN IN THE INTI BLOCK.
IN THIS WE USE A KEYWORD THAT IS "this" IT ALWAYS CALL PROPERTIES OF THE CLASS NOT THE PARAMETERS
WHEN THE OBJECT CREATED IT WILL FIRST EXECUTE THE ( INIT BLOCK )

 */


class User(var name: String,var lastName: String, age: Int){

    var age = age

    init {
        if(age > 18){
            this.age = age // IN THIS "this" KEYWORD ALWAYS CALL THE PROPERTIES NOT THE PARAMETER USING "this" KEYWORD
            println("THIS USER IS VALID CUS OF THE AGE IS GREATER/EQUAL THEN OUR REQUIREMENT.")
        }else{
            this.age = age
            println("THE AGE IS LOWER THEN 18")
        }
    }


}
