fun main(){  // FROM THAT MAIN FUNCTION YOUR PROGRAMME KNOW THAT THIS IS THE STARTING POINT OF MY CODE

    var userName: String = "Anil" // THE STRING IS IN GRAY BECAUSE IT HAS REDUNDANT THE COMPILER KNOW FROM ITS VALUE BCUS THE VALUE IN DOUBLE QOUTED
                                    // AND DOUBLE QOUTED MEANS IT IS STRING DATA TYPE .

    userName = "Anil Prajapat" // IT OVERRIDE YOU FIRST ASSIGNING VALUE

    val age: Int = 28 // IT CANNOT BE REASSIGNED AFTER THIS ASSIGN

    println("Hello $userName you are now $age, Congrulation") // HERE YOU PASS THE VALIABLE TO CALL THAT SPECIFIC VALUE


}